Traceback (most recent call last):
  File "/Users/wernph/anaconda3/envs/dataViz/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/wernph/anaconda3/envs/dataViz/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/wernph/anaconda3/envs/dataViz/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/wernph/anaconda3/envs/dataViz/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/wernph/anaconda3/envs/dataViz/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/wernph/anaconda3/envs/dataViz/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/wernph/anaconda3/envs/dataViz/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# mean vs. median

# data structure to use for the table
table_mean = [
    ["Mean", "Median"], 
    [np.round(diamonds['depth'].mean(), 1), diamonds['depth'].median()]
]
print(tabulate(table_mean)) 
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[7], line 6[0m
[1;32m      1[0m [38;5;66;03m# mean vs. median[39;00m
[1;32m      2[0m 
[1;32m      3[0m [38;5;66;03m# data structure to use for the table[39;00m
[1;32m      4[0m table_mean [38;5;241m=[39m [
[1;32m      5[0m     [[38;5;124m"[39m[38;5;124mMean[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mMedian[39m[38;5;124m"[39m], 
[0;32m----> 6[0m     [[43mnp[49m[38;5;241m.[39mround(diamonds[[38;5;124m'[39m[38;5;124mdepth[39m[38;5;124m'[39m][38;5;241m.[39mmean(), [38;5;241m1[39m), diamonds[[38;5;124m'[39m[38;5;124mdepth[39m[38;5;124m'[39m][38;5;241m.[39mmedian()]
[1;32m      7[0m ]
[1;32m      8[0m [38;5;28mprint[39m(tabulate(table_mean)) 

[0;31mNameError[0m: name 'np' is not defined

